import numpy as np

def compute_regression_classifier(feature_vectors: np.ndarray, class_matrix: np.ndarray) -> np.ndarray:
    """
    Computes a linear regression classifier (W), given a set of feature vectors (F) 
    and a class matrix (V) according to the function W = (F'F)^-1 (F'V).

    Args:
        feature_vectors (np.ndarray): a list of feature vectors (F).
        class_matrix (np.ndarray): a list of one-hot encoded class-label vectors (V).

    Returns:
        np.ndarray: a linear regression classifier (W).
    """
    return np.matmul(
                np.linalg.inv(
                    np.matmul(feature_vectors.transpose(), feature_vectors)
                ), 
                np.matmul(feature_vectors.transpose(), class_matrix)
            )


def compute_MSE(regression_classifier: np.ndarray, feature_vectors: np.ndarray, class_matrix: np.ndarray) -> float:
    """
    Computes the Mean Squared Error (MSE) given a linear regression classifier,
    a set of feature vectors and a class matrix, based on the error between the
    class matrix and the product of the regression classifier and feature vectors.

    Args:
        regression_classifier (np.ndarray): linear regression classifier.
        feature_vectors (np.ndarray): a list of feature vectors.
        class_matrix (np.ndarray): a list of one-hot encoded class-label vectors.

    Returns:
        float: the MSE.
    """
    return sum([np.linalg.norm(class_matrix[idx] - np.matmul(regression_classifier.transpose(), feature_vector))**2 for idx, feature_vector in enumerate(feature_vectors)]) / len(feature_vectors)


def compute_mismatch(regression_classifier, feature_vectors, class_matrix):
    """
    Computes the fraction of mis-classified data points. Classification is done
    by taking the index of the highest value in the output vector per datapoint.
    Output vectors are generated by multiplying the regression classifier and the
    feature vectors. Misclassification is when this index is not the same as the
    index of the 1 in the one-hot encoded vector corresponding to this data point.

    Args:
        regression_classifier (np.ndarray): linear regression classifier.
        feature_vectors (np.ndarray): a list of feature vectors.
        class_matrix (np.ndarray): a list of one-hot encoded class-label vectors.

    Returns:
        float: the fraction of mis-classified data points.
    """
    return sum(
        [0 if np.argmax(class_matrix[idx]) == np.argmax(np.matmul(regression_classifier.transpose(), feature_vector)) 
           else 1 
           for idx, feature_vector in enumerate(feature_vectors)]
                ) / len(feature_vectors)
